title: Kylian Eury
description: Développement web et logiciel
site_title: 'Kylian Eury - Portfolio'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: razor7877
blog_url: https://razor7877.github.io
email: kylian.eury@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 